services:
  mock-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SERVICE_NAME}
    ports:
      - "${PORT}:80"
    environment:
      - NODE_ENV=production
    restart: always
